# Generated by Django 2.1.2 on 2018-11-20 01:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_set',
            new_name='dataO',
        ),
    ]
